api:
  build: ./rba-build-light-distributor/
  container_name: api
  links:
    - db
  ports:
    - 9001:80
  environment:
    - BUILD_LIGHT_PROXY_DB_CONN=mongodb://db/usblight
    - BUILD_LIGHT_PROXY_API_PORT=80
    - BUILD_LIGHT_PROXY_LOG_LEVEL=info
  restart: always
  net: "bridge"

web:
  build: ./rba-build-light-web/
  container_name: web
  links:
    - api
  restart: always
  ports:
    - 9000:80
  environment:
    - BUILD_LIGHT_WEB_PORT=80
    - BUILD_LIGHT_API_URL=api
  net: "bridge"

db:
  image: 'mongo:latest'
  container_name: db
  volumes:
    - /volumes/build-light/db:/data/db
  ports:
    - '27017:27017'